### ISSUE TITLE
pkgAcquire::Run (13: Permission denied)

### ISSUE THREAD

**Issue by mobluse** [lharsfalvi/vice-roms-deb#1]
When I installed it using:
`sudo apt install /home/pi/vice-roms-deb/vice-roms_3.7.1-1_all.deb`
I got an error:
`N: Download is performed unsandboxed as root as file '/home/pi/vice-roms-deb/vice-roms_3.7.1-1_all.deb' couldn't be accessed by user '_apt'. - pkgAcquire::Run (13: Permission denied)`
But `x64` still worked.

Then I did:
`sudo apt purge vice-roms`
As expected `x64` didn't work due to lack of ROM.

Then I installed it using:
`sudo dpkg -i ~/vice-roms-deb/vice-roms_3.7.1-1_all.deb`
That went well without errors and `x64` etc worked.

I think the latter method to install is better since no confusing error.

BTW great system!

**Comment by lharsfalvi** [comment]
Yes, apt has a separate mechanism for downloading packages, which is executed under a non-privileged account. Now when some package has to be fetched from a local directory, but, the file is on a restricted path (i.e. some user's own home directory, which is only accessible for the user and root), apt notices that it couldn't grab it, and reverts to access it as root.

I don't know why I particularly chose to use the apt method there TBH (maybe just "out of habit"), and given the reason, I've never bothered about apt complaining either. Anyway, I have updated the readme (in fact also updated it at a few other places).

Thanks. Well, this is still a hack, nothing serious there :-D, yet it can be convenient to use, at least in spite of having to grab and fiddling with ROM files manually. I'm happy that you could use it with success, and as I guess, that's also yet another platform where the thing proved to just work flawlessly, a good news on it's own.
